#image: dclong/gitpod:blog_070203
image: dclong/gitpod
ports:
  - port: 8888
tasks:
  - command: . /scripts/gitpod.sh
  - command: ./init.sh
vscode:
  extensions:
    - asvetliakov.vscode-neovim
    - ms-python.python
