#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals
import os
# remove old files
os.system('rm -rf output/*')
#-------------------------------------------------------------------------
__blog_dir__ = os.environ["blog_dir"]
# !!! http:// is necessary
__home_url__ = "http://y570.stat.iastate.edu:8000"
__relative_url__ = ""
#-------------------------------------------------------------------------
SITEURL = os.path.join(__home_url__, __relative_url__)
SITESUBTITLE = "And let it direct your passion with reason."
AUTHOR = 'Ben Chuanlong Du'
SITENAME = "Ben Chuanlong Du's Blog"
# Times and dates
DEFAULT_DATE_FORMAT = '%b %d, %Y'
TIMEZONE = 'US/Pacific'
DEFAULT_LANG = u'en'

# pages
PAGE_DIR = "pages"
DISPLAY_PAGES_ON_MENU = False

# Set the article URL
ARTICLE_URL = 'blog/{slug}/'
ARTICLE_SAVE_AS = 'blog/{slug}/index.html'

# Title menu options
MENUITEMS = [
        ('Home', SITEURL),
        ('English', os.path.join(SITEURL, "en")), 
        ('中文', os.path.join(SITEURL, "cn")), 
        ('Miscellanea', os.path.join(SITEURL, "misc")), 
        ]

NEWEST_FIRST_ARCHIVES = True

# tag cloud
TAG_CLOUD_STEPS = 10
TAG_CLOUD_MAX_ITEMS = 100

#Github include settings
GITHUB_USER = 'dclong'
GITHUB_REPO_COUNT = 3
GITHUB_SKIP_FORK = True
GITHUB_SHOW_USER_LINK = True

# Blogroll
#LINKS =  (('Pelican', 'http://docs.notmyidea.org/alexis/pelican/'),
#          ('Python.org', 'http://python.org'),
#          ('Jinja2', 'http://jinja.pocoo.org'),
#          ('You can modify those links in your config file', '#'),)

# Social widget
SOCIAL = (('LinkedIn', 'http://www.linkedin.com/pub/chuanlong-ben-du/21/9b2/123/'),
            ('Twitter', 'https://twitter.com/longendu'),
            ('Facebook', 'https://www.facebook.com/chuanlong.du'))

DEFAULT_PAGINATION = 6

# STATIC_OUT_DIR requires https://github.com/jakevdp/pelican/tree/specify-static
#STATIC_OUT_DIR = ''
#FILES_TO_COPY = [('favicon.png', 'favicon.png')]

# This requires Pelican 3.3+
STATIC_PATHS = [
            'images', 
            'figures', 
            'downloads', 
            'favicon.png', 
            'media',
            'CNAME',
            'readme.md',
        ]

CODE_DIR = 'downloads/code'
NOTEBOOK_DIR = 'downloads/notebooks'


# theme 
CSS_FILE = 'main.css'
THEME = os.path.join(__blog_dir__, "themes/octopress_0")
# plugins
PLUGIN_PATHS = [os.path.join(__blog_dir__, 'plugins')]
PLUGINS = [
        'latex',
        'summary', 
        'liquid_tags.img', 
        'liquid_tags.video', 
        'liquid_tags.include_code', 
        'liquid_tags.notebook', 
        'liquid_tags.literal',
    ]

# The theme file should be updated so that the base header contains the line:
#
#  {% if EXTRA_HEADER %}
#    {{ EXTRA_HEADER }}
#  {% endif %}
# 
# This header file is automatically generated by the notebook plugin

if not os.path.exists('_nb_header.html'):
    import warnings
    warnings.warn("_nb_header.html not found.  "
                  "Rerun make html to finalize build.")
else:
    EXTRA_HEADER = open('_nb_header.html').read().decode('utf-8')

# disqus comment
DISQUS_SITENAME = "dclong"

# Sharing
TWITTER_USER = 'longendu'
GOOGLE_PLUS_USER = 'duchuanlong'
GOOGLE_PLUS_ONE = True
GOOGLE_PLUS_HIDDEN = False
FACEBOOK_LIKE = True
TWITTER_TWEET_BUTTON = True
TWITTER_LATEST_TWEETS = True
TWITTER_FOLLOW_BUTTON = True
TWITTER_TWEET_COUNT = 3
TWITTER_SHOW_REPLIES = 'false'
TWITTER_SHOW_FOLLOWER_COUNT = 'true'


# RSS/Atom feeds
FEED_DOMAIN = SITEURL
FEED_ATOM = 'atom.xml'
# FEED_RSS = 


# Search
# SEARCH_BOX = True
SITESEARCH = "http://www.google.com/search"

# google analytics
GOOGLE_ANALYTICS = 'UA-30259661-1'

# Feed generation is usually not desired when developing
#FEED_ALL_ATOM = None
#CATEGORY_FEED_ATOM = None
#TRANSLATION_FEED_ATOM = None



# Uncomment following line if you want document-relative URLs when developing
#RELATIVE_URLS = True
