[package]
name = "test_log"
version = "0.1.0"
authors = ["Benjamin Du <longendu@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
simple_logger = "1.11.0"
thiserror = "1.0.25"

