name: Create PR To main
on:
  push:
    branches-ignore:
      - main
      - _**
jobs:
  create_pr_main:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sudo env UV_INSTALL_DIR="/usr/local/bin" sh
      - name: Create PR To main
        run: | 
          uvx --from github-rest-api@latest create_pull_request \
            --head-branch ${{ github.ref_name }} \
            --base-branch main \
            --token ${{ secrets.ACTIONS_TOKEN }}

