name: Publish Blog
on:
  push:
    branches: [ master ]
jobs:
  publish_blog:
    runs-on: self-hosted
    container:
      image: dclong/jupyterhub-ds:blog_071520
      volumes:
        - /home/dclong/.ssh:/ssh
    steps:
      #- uses: actions/checkout@v3
      #  with:
      #    token: ${{secrets.GITHUBACTIONS}}
      - name: Config SSH
        run: |
          mkdir -p /root/.ssh
          cp -r /ssh/* /root/.ssh/
          chmod 600 /root/.ssh/*
          sed -i 's_^Host \*$_Host *\n    StrictHostKeyChecking accept-new_' /root/.ssh/config
      - name: Clone Repo
        run: |
          pwd
          cd ..
          rm -rf blog/
          git clone --depth 1 git@github.com:legendu-net/blog.git
          cd blog
          pwd
          ls -lh
          git remote -v
      - name: Install dependencies
        run: |
          pwd
          #wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb -O /tmp/libssl.deb
          #wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.20_amd64.deb -O /tmp/libssl.deb
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb -O /tmp/libssl.deb
          dpkg -i /tmp/libssl.deb
          python3 -m pip install --user "pelican-jupyter==0.10.0"
      - name: Build and Publish to GitHub Pages
        run: |
          pwd
          git config --global --add safe.directory '*'
          git config --global user.email "longendu@yahoo.com"
          git config --global user.name "Ben Du"
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          python3 ./blog.py p -ecmo

