name: Publish Blog
on:
  push:
    branches: [ master ]
jobs:
  publish_blog:
    runs-on: self-hosted
    container:
      image: dclong/jupyterhub-ds:blog_071520
      volumes:
        - /home/dclong/.ssh:/ssh
    steps:
      #- uses: actions/checkout@v3
      #  with:
      #    token: ${{secrets.GITHUBACTIONS}}
      - name: Config SSH
        run: |
          mkdir -p /root/.ssh
          cp -r /ssh/* /root/.ssh/
          chmod 600 /root/.ssh/*
      - name: Clone Repo
        run: |
          rm -rf blog/
          git clone git@github.com:legendu-net/blog.git
          cd blog
          ls -lh
          git remote -v
      - name: Install dependencies
        run: |
          ./init.sh
      - name: Build and Publish to GitHub Pages
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "longendu@yahoo.com"
          git config --global user.name "Ben Du"
          ./blog.py p -ecmo

