name: Publish Blog
on:
  push:
    branches: [ master ]
jobs:
  publish_blog:
    runs-on: ubuntu-latest
    container: dclong/jupyterlab:blog
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.GITHUBACTIONS}}
    - name: Install dependencies
      run: |
        ./init.sh
    - name: Build and Publish to GitHub Pages
      run: |
        git config --global --add safe.directory '*'
        git config --global user.email "longendu@yahoo.com"
        git config --global user.name "Ben Du"
        ./blog.py p --https -ecmoF
