name: Publish Blog
on:
  push:
    branches: [ master ]
jobs:
  publish_blog:
    runs-on: ubuntu-latest
    container: dclong/jupyterlab:blog
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        ./init.sh
    - name: Build and Publish to GitHub Pages
      run: |
        git config --global --add safe.directory '*'
        git config --global user.email "longendu@yahoo.com"
        git config --global user.name "Ben Du"
        git config --global credential.helper store
        echo https://${{secrets.GITHUBACTIONS}}@github.com/legendu-net/blog >> ~/.git-credentials
        ./blog.py p -ecmoF
